### ISSUE TITLE
Is there a way to override button text?

### ISSUE THREAD

**Issue by Sn4kehead** [fongandrew/meteor-user-settings#1]
Hi, I was wondering if it was possible to override the save button text. I see in your template you use

{{> saveButton buttonText="Resend?"}},

but I can't seem to get this to work from my code, without touching anything in .meteor as it gets autogenerated anyway. I'm new to Meteor so the answer might be obvious, but please help me out if you can!!
I also tried copy-pasting your template and calling that instead of {{>accountSettings}} but it doesn't like the duplicate names (and when I change the names it just doesn't display anything). Thank you in advance :)

**Comment by fongandrew** [comment]
It's been a while since I've looked at this code, but I don't think there's any way to modify the save button text directly. I've mostly switched over to React so there aren't any plans to update this package going forward.

That said, the reason changing the name of the `accountSettings` template doesn't work is that the corresponding code in https://github.com/fongandrew/meteor-user-settings/blob/master/account_settings.js wasn't also changed. So what you could try doing is copying/forking the _entire_ package, rather than just the one template.

To do that, create a `packages/<yourname>:user-settings` directory in your Meteor project and copy my package into there. Then edit the template to use your new button text. Edit `package.js` and change `fongandrew:user-settings` to `<yourname>:user-settings`.

Then do `meteor remove fongandrew:user-settings` and `meteor add <yourname>:user-settings`. `{{> accountSettings}}` should now be using your new template changes.

**Comment by Sn4kehead** [comment]
Right, thank you for your quick reply!
